Repository jupyter/jupyter_core, pull requests merged in 2022-12, with the labels that each got.

#321 Adopt ruff and address lint
  .github/dependabot.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  jupyter_core/application.py
  jupyter_core/paths.py
  pyproject.toml
Labels: maintenance

#325 Fix lint
  .pre-commit-config.yaml
  jupyter_core/application.py
  pyproject.toml
Labels: maintenance

#324 Don't treat the conda root env as an env
  jupyter_core/application.py
  jupyter_core/paths.py
  jupyter_core/tests/test_paths.py
  pyproject.toml
Labels: bug

#323 Only prefer envs owned by the current user
  jupyter_core/paths.py
  jupyter_core/tests/test_paths.py
Labels: enhancement

#327 Add spell check and ensure docstrings
  .github/workflows/test.yml
  .pre-commit-config.yaml
  docs/conf.py
  jupyter_core/application.py
  jupyter_core/command.py
  jupyter_core/migrate.py
  jupyter_core/paths.py
  pyproject.toml
Labels: maintenance

#328 Add api docs
  .github/workflows/test.yml
  docs/api/jupyter_core.rst
  docs/api/jupyter_core.utils.rst
  docs/api/modules.rst
  docs/conf.py
  docs/index.rst
  docs/paths.rst
  jupyter_core/migrate.py
  jupyter_core/utils/__init__.py
  pyproject.toml
Labels: documentation
