Repository jupyter/jupyter_core, pull requests merged in 2022-11, with the labels that each got.

#302 Require Python 3.8+
  .github/workflows/test.yml
  .pre-commit-config.yaml
  pyproject.toml
Labels: maintenance

#304 Add more typing
  .github/workflows/test.yml
  .pre-commit-config.yaml
  docs/conf.py
  jupyter_core/application.py
  jupyter_core/command.py
  jupyter_core/migrate.py
  jupyter_core/paths.py
  jupyter_core/troubleshoot.py
  pyproject.toml
Labels: maintenance

#305 Adopt jupyter releaser
  .github/workflows/check-release.yml
  .github/workflows/enforce-label.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  COPYING.md
  README.md
  docs/changelog.rst
  docs/conf.py
  docs/requirements.txt
  jupyter_core/version.py
Labels: maintenance

#306 Add dependabot
  .github/dependabot.yml
Labels: maintenance

#312 CI Cleanup
  .github/workflows/check-release.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .readthedocs.yaml
  codecov.yml
  docs/requirements.txt
  jupyter_core/tests/test_command.py
  pyproject.toml
  readthedocs.yml
Labels: maintenance

#314 Clean up workflows and add badges
  .github/workflows/test.yml
  README.md
Labels: maintenance, documentation

#315 Add run_sync and ensure_async functions
  jupyter_core/tests/test_async.py
  jupyter_core/utils/__init__.py
Labels: enhancement

#316 Add more path tests
  jupyter_core/tests/test_paths.py
Labels: maintenance

#317 [4.x] Add run_sync and ensure_async functions
  .pre-commit-config.yaml
  COPYING.md
  README.md
  jupyter_core/command.py
  jupyter_core/tests/test_async.py
  jupyter_core/utils/__init__.py
Labels: enhancement
