Repository jupyter/jupyter_core, pull requests merged in 2023-01, with the labels that each got.

#326 Maint: Some more precise typing.
  jupyter_core/utils/__init__.py
Labels: maintenance

#330 MAINT: Coro is not coro-function.
  .pre-commit-config.yaml
  jupyter_core/utils/__init__.py
Labels: maintenance

#332 Add check-wheel-contents ignore
  pyproject.toml
Labels: maintenance

#333 Clear the test environment before each function run
  jupyter_core/tests/test_command.py
  jupyter_core/tests/test_paths.py
Labels: bug

#335 Suppress any exception in _do_i_own shortcut
  jupyter_core/paths.py
Labels: bug

#336 MAINT: Don't format logs in log call.
  jupyter_core/application.py
  jupyter_core/migrate.py
Labels: maintenance

#337 Set up shell command-line tab-completion for jupyter and subcommands
  examples/jupyter-completion.bash
  jupyter_core/command.py
  jupyter_core/migrate.py
  jupyter_core/troubleshoot.py
  scripts/jupyter-migrate
Labels: enhancement

#338 Add more linting
  .pre-commit-config.yaml
  docs/conf.py
  jupyter_core/command.py
  jupyter_core/migrate.py
  jupyter_core/paths.py
  jupyter_core/tests/test_command.py
  jupyter_core/tests/test_paths.py
  jupyter_core/troubleshoot.py
  jupyter_core/utils/__init__.py
  jupyter_core/version.py
  pyproject.toml
Labels: maintenance
